// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mcamiyvffysvwulwsvch.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1jYW1peXZmZnlzdnd1bHdzdmNoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzOTM1ODYsImV4cCI6MjA2OTk2OTU4Nn0.Rnfu6sKlTx-9pOpb_CIvb0xKjAaX-mOLz_3-Eknn5N4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});